# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommentsApp', '0004_auto_20161207_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='children',
            field=models.ManyToManyField(null=True, related_name='_comment_children_+', to='CommentsApp.Comment'),
        ),
    ]
