# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommentsApp', '0005_comment_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='children',
            field=models.ManyToManyField(related_name='_comment_children_+', to='CommentsApp.Comment'),
        ),
    ]
